# Generated by Django 3.1.5 on 2023-05-15 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_auto_20200822_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='myapi.task'),
        ),
    ]
